# Generated by Django 4.2.4 on 2023-08-10 13:59

import MyPetstagramProject.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pet_photos/', validators=[MyPetstagramProject.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
